import students from "@/data/students.json";
import gallery from "@/data/gallery.json";
import messages from "@/data/messages.json";
import { GALLERY_PHOTOS } from "@/lib/galleryManifest";
import { YEARBOOK_PAGES } from "@/lib/yearbookManifest";
import type { Student, GalleryItem, GalleryPhoto, Dedication } from "@/types";

export function getStudents(): Student[] {
  return students as Student[];
}

export function getGallery(): GalleryItem[] {
  return gallery as GalleryItem[];
}

export function getSeedMessages(): Dedication[] {
  return messages as Dedication[];
}

/**
 * Canva flipbook page exports (1.png, 2.png, …), numeric-sorted. Empty array =
 * no exports yet; the flipbook falls back to its generated student spreads.
 *
 * Read from a build-time manifest (lib/yearbookManifest, generated by
 * scripts/gen-media-manifests.mjs) rather than scanning public/ at runtime —
 * so serverless functions never bundle the page images. Regenerate after
 * adding pages with `npm run media:manifest`.
 */
export function getYearbookPages(): string[] {
  return YEARBOOK_PAGES;
}

/**
 * Gallery photos, each tagged with a capture time and sorted oldest → recent.
 *
 * Comes from a build-time manifest (lib/galleryManifest, generated by
 * scripts/gen-media-manifests.mjs, which resolves each time from filename →
 * EXIF → file mtime). The actual image files stay static CDN assets and are
 * never read by — or bundled into — a serverless function. Regenerate after
 * adding photos with `npm run media:manifest`.
 */
export function getGalleryPhotos(): GalleryPhoto[] {
  return GALLERY_PHOTOS;
}

/** Case/whitespace-insensitive comparison used to validate registrations. */
export function normalizeName(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, " ");
}

export function findStudentByName(name: string): Student | undefined {
  const target = normalizeName(name);
  return getStudents().find((s) => normalizeName(s.fullName) === target);
}

export function searchStudents(query: string): Student[] {
  const q = query.trim().toLowerCase();
  if (!q) return getStudents();
  return getStudents().filter(
    (s) =>
      s.fullName.toLowerCase().includes(q) ||
      s.nickname.toLowerCase().includes(q) ||
      s.instagram.toLowerCase().includes(q)
  );
}
