// AUTO-GENERATED by scripts/gen-media-manifests.mjs — do not edit by hand.
// Regenerate with `npm run media:manifest` (also runs before every build).

import type { GalleryPhoto } from "@/types";

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    "src": "/gallery/img_20221003.webp",
    "time": 1664769600000,
    "dated": true
  },
  {
    "src": "/gallery/img_20221003_01.webp",
    "time": 1664769600000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20221124_163446.jpg",
    "time": 1669278886000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20221201_162719.jpg",
    "time": 1669883239000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20231031_114530.jpg",
    "time": 1698723930000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20231114_115450.jpg",
    "time": 1699934090000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20231114_115453.jpg",
    "time": 1699934093000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_100654.jpg",
    "time": 1710122814000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_100710.jpg",
    "time": 1710122830000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_100718.jpg",
    "time": 1710122838000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_101347.jpg",
    "time": 1710123227000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_101430.jpg",
    "time": 1710123270000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_101432.jpg",
    "time": 1710123272000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_103718.jpg",
    "time": 1710124638000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_111417.jpg",
    "time": 1710126857000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_111424.jpg",
    "time": 1710126864000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_111438.jpg",
    "time": 1710126878000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_111457.jpg",
    "time": 1710126897000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_111501.jpg",
    "time": 1710126901000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_111854.jpg",
    "time": 1710127134000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_111855.jpg",
    "time": 1710127135000,
    "dated": true
  },
  {
    "src": "/gallery/20240311_122504.jpg",
    "time": 1710131104000,
    "dated": true
  },
  {
    "src": "/gallery/20240312_125456.jpg",
    "time": 1710219296000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20240316_173011.jpg",
    "time": 1710581411000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20240316_173014.jpg",
    "time": 1710581414000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20240316_173022.jpg",
    "time": 1710581422000,
    "dated": true
  },
  {
    "src": "/gallery/20240418_064445.jpg",
    "time": 1713393885000,
    "dated": true
  },
  {
    "src": "/gallery/20240418_064457.jpg",
    "time": 1713393897000,
    "dated": true
  },
  {
    "src": "/gallery/20240418_080409.jpg",
    "time": 1713398649000,
    "dated": true
  },
  {
    "src": "/gallery/20240418.jpeg",
    "time": 1713412800000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20240423_121432.jpg",
    "time": 1713845672000,
    "dated": true
  },
  {
    "src": "/gallery/20240502.jpeg",
    "time": 1714622400000,
    "dated": true
  },
  {
    "src": "/gallery/20240513_103215.jpg",
    "time": 1715567535000,
    "dated": true
  },
  {
    "src": "/gallery/20240513_103217.jpg",
    "time": 1715567537000,
    "dated": true
  },
  {
    "src": "/gallery/20240513_103231.jpg",
    "time": 1715567551000,
    "dated": true
  },
  {
    "src": "/gallery/20240513_103232.jpg",
    "time": 1715567552000,
    "dated": true
  },
  {
    "src": "/gallery/20240514_094223.jpg",
    "time": 1715650943000,
    "dated": true
  },
  {
    "src": "/gallery/20240514_094228.jpg",
    "time": 1715650948000,
    "dated": true
  },
  {
    "src": "/gallery/20240515_113741.jpg",
    "time": 1715744261000,
    "dated": true
  },
  {
    "src": "/gallery/20240515_113751.jpg",
    "time": 1715744271000,
    "dated": true
  },
  {
    "src": "/gallery/20240515_114034.jpg",
    "time": 1715744434000,
    "dated": true
  },
  {
    "src": "/gallery/20240515_114101.jpg",
    "time": 1715744461000,
    "dated": true
  },
  {
    "src": "/gallery/20240515_114136.jpg",
    "time": 1715744496000,
    "dated": true
  },
  {
    "src": "/gallery/20240515_114144.jpg",
    "time": 1715744504000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20240515_114809.jpg",
    "time": 1715744889000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20240515_114829.jpg",
    "time": 1715744909000,
    "dated": true
  },
  {
    "src": "/gallery/20240515.jpg",
    "time": 1715745600000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20240515_162806.jpg",
    "time": 1715761686000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20240515_162809.jpg",
    "time": 1715761689000,
    "dated": true
  },
  {
    "src": "/gallery/20240913_171954.jpg",
    "time": 1726219194000,
    "dated": true
  },
  {
    "src": "/gallery/20241123_134202.jpg",
    "time": 1732340522000,
    "dated": true
  },
  {
    "src": "/gallery/20241202_135714.jpg",
    "time": 1733119034000,
    "dated": true
  },
  {
    "src": "/gallery/20241202_135917.jpg",
    "time": 1733119157000,
    "dated": true
  },
  {
    "src": "/gallery/20241202_135923.jpg",
    "time": 1733119163000,
    "dated": true
  },
  {
    "src": "/gallery/20250123_143947.jpg",
    "time": 1737614387000,
    "dated": true
  },
  {
    "src": "/gallery/20250129_155720.jpg",
    "time": 1738137440000,
    "dated": true
  },
  {
    "src": "/gallery/20250129_155735.jpg",
    "time": 1738137455000,
    "dated": true
  },
  {
    "src": "/gallery/20250201.jpg",
    "time": 1738382400000,
    "dated": true
  },
  {
    "src": "/gallery/20250201_15.jpg",
    "time": 1738382400000,
    "dated": true
  },
  {
    "src": "/gallery/20250304.jpg",
    "time": 1741060800000,
    "dated": true
  },
  {
    "src": "/gallery/20250305.jpg",
    "time": 1741147200000,
    "dated": true
  },
  {
    "src": "/gallery/20250305_01.jpg",
    "time": 1741147200000,
    "dated": true
  },
  {
    "src": "/gallery/20250305_02.jpg",
    "time": 1741147200000,
    "dated": true
  },
  {
    "src": "/gallery/20250305_1655.jpg",
    "time": 1741147200000,
    "dated": true
  },
  {
    "src": "/gallery/20250305_22.jpeg",
    "time": 1741147200000,
    "dated": true
  },
  {
    "src": "/gallery/20250305_30.jpg",
    "time": 1741147200000,
    "dated": true
  },
  {
    "src": "/gallery/20250306_061039.jpg",
    "time": 1741212639000,
    "dated": true
  },
  {
    "src": "/gallery/20250306.JPG",
    "time": 1741233600000,
    "dated": true
  },
  {
    "src": "/gallery/20250306_05.jpg",
    "time": 1741233600000,
    "dated": true
  },
  {
    "src": "/gallery/20250306_08.jpg",
    "time": 1741233600000,
    "dated": true
  },
  {
    "src": "/gallery/20250307.JPEG",
    "time": 1741320000000,
    "dated": true
  },
  {
    "src": "/gallery/20250307_12.JPG",
    "time": 1741320000000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20250310_105325.jpg",
    "time": 1741575205000,
    "dated": true
  },
  {
    "src": "/gallery/20250326_140337.jpg",
    "time": 1742969017000,
    "dated": true
  },
  {
    "src": "/gallery/20250327_095829.jpg",
    "time": 1743040709000,
    "dated": true
  },
  {
    "src": "/gallery/20250421_132552.jpg",
    "time": 1745213152000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20250423_110756.jpg",
    "time": 1745377676000,
    "dated": true
  },
  {
    "src": "/gallery/20250423_175843.jpg",
    "time": 1745402323000,
    "dated": true
  },
  {
    "src": "/gallery/20250429_135946.jpg",
    "time": 1745906386000,
    "dated": true
  },
  {
    "src": "/gallery/20250609_125224.jpg",
    "time": 1749444744000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20250717_133827.jpg",
    "time": 1752730707000,
    "dated": true
  },
  {
    "src": "/gallery/20250829_113224.jpg",
    "time": 1756438344000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_2885_20250902_090418_3600.jpeg",
    "time": 1756775058000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_2886_20250902_090427_3600.jpeg",
    "time": 1756775067000,
    "dated": true
  },
  {
    "src": "/gallery/20250920_095031.jpg",
    "time": 1758333031000,
    "dated": true
  },
  {
    "src": "/gallery/20250920.jpg",
    "time": 1758340800000,
    "dated": true
  },
  {
    "src": "/gallery/VideoCapture_20250930-172317.jpg",
    "time": 1759224197000,
    "dated": true
  },
  {
    "src": "/gallery/20251001_110500.jpg",
    "time": 1759287900000,
    "dated": true
  },
  {
    "src": "/gallery/20251024_200913.jpg",
    "time": 1761307753000,
    "dated": true
  },
  {
    "src": "/gallery/20251028_172544.jpg",
    "time": 1761643544000,
    "dated": true
  },
  {
    "src": "/gallery/20251104_101541.jpg",
    "time": 1762222541000,
    "dated": true
  },
  {
    "src": "/gallery/20251202_102712.jpg",
    "time": 1764642432000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20251202_180405.jpg",
    "time": 1764669845000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20251202_180439.jpg",
    "time": 1764669879000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20251202_180443.jpg",
    "time": 1764669883000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20251202_180452.jpg",
    "time": 1764669892000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20251202_180504.jpg",
    "time": 1764669904000,
    "dated": true
  },
  {
    "src": "/gallery/IMG_20251202_180511.jpg",
    "time": 1764669911000,
    "dated": true
  },
  {
    "src": "/gallery/20251212_080812.jpg",
    "time": 1765498092000,
    "dated": true
  },
  {
    "src": "/gallery/20260110_124824.jpg",
    "time": 1768020504000,
    "dated": true
  },
  {
    "src": "/gallery/20260120.jpg",
    "time": 1768881600000,
    "dated": true
  },
  {
    "src": "/gallery/20260120_01.jpg",
    "time": 1768881600000,
    "dated": true
  },
  {
    "src": "/gallery/20260124_111438.jpg",
    "time": 1769224478000,
    "dated": true
  },
  {
    "src": "/gallery/FullSizeRender.jpg",
    "time": 1769224480000,
    "dated": true
  },
  {
    "src": "/gallery/20260126_092146.jpg",
    "time": 1769390506000,
    "dated": true
  },
  {
    "src": "/gallery/20260207_060038.jpg",
    "time": 1770415238000,
    "dated": true
  },
  {
    "src": "/gallery/20260209.jpeg",
    "time": 1770609600000,
    "dated": true
  },
  {
    "src": "/gallery/20260209.jpg",
    "time": 1770609600000,
    "dated": true
  },
  {
    "src": "/gallery/20260211.JPG",
    "time": 1770782400000,
    "dated": true
  },
  {
    "src": "/gallery/3D184CD4-4976-4F26-A614-98964D1D27D9.jpg",
    "time": 1773122273000,
    "dated": true
  },
  {
    "src": "/gallery/20260312.jpg",
    "time": 1773288000000,
    "dated": true
  },
  {
    "src": "/gallery/20260325.jpg",
    "time": 1774411200000,
    "dated": true
  },
  {
    "src": "/gallery/20260325_01.jpg",
    "time": 1774411200000,
    "dated": true
  },
  {
    "src": "/gallery/20260425.jpg",
    "time": 1777089600000,
    "dated": true
  },
  {
    "src": "/gallery/20260425_01.jpg",
    "time": 1777089600000,
    "dated": true
  },
  {
    "src": "/gallery/20260425_04.jpg",
    "time": 1777089600000,
    "dated": true
  },
  {
    "src": "/gallery/20260511_192710.jpg",
    "time": 1778498830000,
    "dated": true
  },
  {
    "src": "/gallery/img26.JPG",
    "time": 1781664300519.2458,
    "dated": false
  },
  {
    "src": "/gallery/IMG_6195.jpg",
    "time": 1781664306611.2976,
    "dated": false
  },
  {
    "src": "/gallery/img.jpg",
    "time": 1781664308862.5164,
    "dated": false
  },
  {
    "src": "/gallery/received_154926620409928.webp",
    "time": 1781675738043.838,
    "dated": false
  },
  {
    "src": "/gallery/4f9bc811-5909-4654-954a-8d40a7ab6544.jpg",
    "time": 1781675869235.066,
    "dated": false
  },
  {
    "src": "/gallery/c2b27728-3c57-4365-8e80-493c27994376.jpg",
    "time": 1781675876299.3247,
    "dated": false
  },
  {
    "src": "/gallery/received_4604016083189609.jpeg",
    "time": 1781677357500.9585,
    "dated": false
  }
];
