// AUTO-GENERATED by scripts/gen-letters-manifest.mjs — do not edit by hand.
// Run `npm run letters:manifest` after adding files to public/letters/.

export const LETTERS: Record<string, string[]> = {
  "a": [
    "/letters/a.png",
    "/letters/a-2.png",
    "/letters/a-3.png",
    "/letters/a-4.png",
    "/letters/a-5.png",
    "/letters/a-6.png"
  ],
  "b": [
    "/letters/b.png",
    "/letters/b-2.png",
    "/letters/b-3.png",
    "/letters/b-4.png",
    "/letters/b-5.png"
  ],
  "c": [
    "/letters/c.png",
    "/letters/c-2.png",
    "/letters/c-3.png",
    "/letters/c-4.png",
    "/letters/c-5.png"
  ],
  "d": [
    "/letters/d.png",
    "/letters/d-2.png",
    "/letters/d-3.png",
    "/letters/d-4.png"
  ],
  "e": [
    "/letters/e.png",
    "/letters/e-2.png",
    "/letters/e-3.png",
    "/letters/e-4.png",
    "/letters/e-5.png",
    "/letters/e-6.png",
    "/letters/e-7.png"
  ],
  "f": [
    "/letters/f.png",
    "/letters/f-2.png",
    "/letters/f-3.png",
    "/letters/f-4.png"
  ],
  "g": [
    "/letters/g.png",
    "/letters/g-2.png",
    "/letters/g-3.png",
    "/letters/g-4.png"
  ],
  "h": [
    "/letters/h.png",
    "/letters/h-2.png",
    "/letters/h-3.png",
    "/letters/h-4.png",
    "/letters/h-5.png"
  ],
  "i": [
    "/letters/i.png",
    "/letters/i-2.png",
    "/letters/i-3.png",
    "/letters/i-4.png"
  ],
  "j": [
    "/letters/j.png",
    "/letters/j-2.png",
    "/letters/j-3.png"
  ],
  "k": [
    "/letters/k.png",
    "/letters/k-2.png",
    "/letters/k-3.png",
    "/letters/k-4.png"
  ],
  "l": [
    "/letters/l.png",
    "/letters/l-2.png",
    "/letters/l-3.png",
    "/letters/l-4.png"
  ],
  "m": [
    "/letters/m.png",
    "/letters/m-2.png",
    "/letters/m-3.png",
    "/letters/m-4.png"
  ],
  "n": [
    "/letters/n.png",
    "/letters/n-2.png",
    "/letters/n-3.png"
  ],
  "o": [
    "/letters/o.png",
    "/letters/o-2.png",
    "/letters/o-3.png",
    "/letters/o-4.png"
  ],
  "p": [
    "/letters/p.png",
    "/letters/p-2.png",
    "/letters/p-3.png",
    "/letters/p-4.png"
  ],
  "q": [
    "/letters/q.png",
    "/letters/q-2.png",
    "/letters/q-3.png"
  ],
  "r": [
    "/letters/r.png",
    "/letters/r-2.png",
    "/letters/r-3.png",
    "/letters/r-4.png"
  ],
  "s": [
    "/letters/s.png",
    "/letters/s-2.png",
    "/letters/s-3.png",
    "/letters/s-4.png"
  ],
  "t": [
    "/letters/t.png",
    "/letters/t-1.png",
    "/letters/t-2.png",
    "/letters/t-3.png"
  ],
  "u": [
    "/letters/u.png",
    "/letters/u-2.png"
  ],
  "v": [
    "/letters/v.png",
    "/letters/v-2.png",
    "/letters/v-3.png",
    "/letters/v-4.png"
  ],
  "w": [
    "/letters/w.png",
    "/letters/w-2.png"
  ],
  "x": [
    "/letters/x.png",
    "/letters/x-2.png"
  ],
  "y": [
    "/letters/y.png",
    "/letters/y-2.png",
    "/letters/y-3.png"
  ],
  "z": [
    "/letters/z.png",
    "/letters/z-2.png"
  ]
};
