// AUTO-GENERATED by scripts/gen-media-manifests.mjs — do not edit by hand.
// Regenerate with `npm run media:manifest` (also runs before every build).

export const YEARBOOK_PAGES: string[] = [
  "/yearbook-pages/1.png",
  "/yearbook-pages/2.png",
  "/yearbook-pages/3.png",
  "/yearbook-pages/4.png",
  "/yearbook-pages/5.png",
  "/yearbook-pages/6.png",
  "/yearbook-pages/7.png",
  "/yearbook-pages/8.png"
];
